openapi: 3.0.0
info:
  title: iCloud-API
  description: ""
  version: "1"
servers:
- url: https://virtserver.swaggerhub.com/PEPPERSGRANTS0H/iCloud/1
  description: SwaggerHub API Auto Mocking
paths: {}
components:
  schemas:
    iCloud-API:
      type: object
      properties:
        id:
          type: integer
          format: int64
